name: Enterprise CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          echo "Hello from build job" > output.txt
          date >> output.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output.txt


  test-job:
     runs-on: ubuntu-latest
     needs: build-job

     steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
         with:
           name: build-output

       - name: Test the artifact
         run: |
           echo "Testing artifact.."
           cat output.txt

           if grep -q "Hello from Build job" output.txt; then
              echo "Test Passed"

           else
              echo "Test Failed"
              exit 1
           fi

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job

    steps:
      - name: Download artificat for deployment
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Deploy artifact
        run: |
          echo "Deploying now.."
          cat output.txt
          echo "Deployment successful"    
